// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb0XFr4eUh2mlV1muFaMdHEc5lm6kr10s',
    appId: '1:809008488136:web:80a36edb844e8f5d424ffd',
    messagingSenderId: '809008488136',
    projectId: 'ascend-b68fd',
    authDomain: 'ascend-b68fd.firebaseapp.com',
    storageBucket: 'ascend-b68fd.firebasestorage.app',
    measurementId: 'G-4W9VQG90DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTUUSa_kP1A5MbtB_5AfyEzBgdWM6uFBY',
    appId: '1:809008488136:android:1288a97cdbf0a971424ffd',
    messagingSenderId: '809008488136',
    projectId: 'ascend-b68fd',
    storageBucket: 'ascend-b68fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAria7S8bjdE-Ce61pQvp0iGhi5_30D1aM',
    appId: '1:809008488136:ios:08d564fbf4d975c2424ffd',
    messagingSenderId: '809008488136',
    projectId: 'ascend-b68fd',
    storageBucket: 'ascend-b68fd.firebasestorage.app',
    iosBundleId: 'com.example.ascend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAria7S8bjdE-Ce61pQvp0iGhi5_30D1aM',
    appId: '1:809008488136:ios:08d564fbf4d975c2424ffd',
    messagingSenderId: '809008488136',
    projectId: 'ascend-b68fd',
    storageBucket: 'ascend-b68fd.firebasestorage.app',
    iosBundleId: 'com.example.ascend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb0XFr4eUh2mlV1muFaMdHEc5lm6kr10s',
    appId: '1:809008488136:web:0d392599be48f19c424ffd',
    messagingSenderId: '809008488136',
    projectId: 'ascend-b68fd',
    authDomain: 'ascend-b68fd.firebaseapp.com',
    storageBucket: 'ascend-b68fd.firebasestorage.app',
    measurementId: 'G-XBJMM33HFJ',
  );
}
